# -*- coding: utf-8 -*-
"""Sending_email_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ku0_WvhFvh-SSxKY2hu6nf3i5hfSfPd2
"""

from twilio.rest import Client

def send_sms(account_sid, auth_token, twilio_phone_number, recipient_phone_number, message_body):
    try:
        client = Client(account_sid, auth_token)

        message = client.messages.create(
            body=message_body,
            from_=twilio_phone_number,
            to=recipient_phone_number
        )

        print("SMS sent successfully!")
        print(f"Message SID: {message.sid}")

    except Exception as e:
        print(f"Error occurred while sending the SMS: {e}")

# Example usage
if __name__ == "Virendra":
    account_sid = 'YOUR_TWILIO_ACCOUNT_SID'
    auth_token = 'YOUR_TWILIO_AUTH_TOKEN'
    twilio_phone_number = 'YOUR_TWILIO_PHONE_NUMBER'  # Format: '+1234567890'
    recipient_phone_number = 'RECIPIENT_PHONE_NUMBER'  # Format: '+1234567890'
    message_body = 'This is a test SMS sent using Python and Twilio!'

    send_sms(account_sid, auth_token, twilio_phone_number, recipient_phone_number, message_body)